name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
      - name: Build Docker Image
        run: docker build -t sainath521/reactjs-app .

      - name: Publish image to Docker Hub
        run: docker push sainath521/reactjs-app:latest   

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Pull image from Docker Hub and deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.143.174.1 << 'EOF'
            docker pull sainath521/reactjs-app:latest
            docker rm -f reactContainer || true
            docker run -d -p 4000:80 --name reactContainer sainath521/reactjs-app:latest
          EOF

