name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sainath521/neolocus-app .

      - name: Publish image to Docker Hub
        run: docker push sainath521/neolocus-app:latest   

  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.143.174.1 << 'EOF'
            sudo bash -c "
              # Pull the latest Docker image
              docker pull sainath521/neolocus-app:latest

              # Stop and remove the old Docker container if it exists
              docker stop neolocusContainer || true
              docker rm neolocusContainer || true

              # Run the new Docker container
              docker run -d -p 4000:4000 --name neolocusContainer sainath521/neolocus-app:latest
            "
          EOF
